### PR TITLE
[FIX] avoid systematic warning when creating new product templates

### PR DESCRIPTION
**Pull request by sbidoul**
@zakiuu @pedrobaeza what do you think about this one?

### CODE REVIEW

**Comment by zakiuu** [comment]
@sbidoul works with the unit tests?

**Comment by pedrobaeza** [comment]
Have you tried testing if it's a NewId? Anyway, if this works, we can accept it as is.

**Comment by sbidoul** [comment]
I'll test with NewId.

**Comment by sbidoul** [comment]
In my test, self.id is always a NewId. So I merge as is.

**Comment by pedrobaeza** [comment]
OK then

**Pull request merged**
